[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-crons"
version = "2.0.1"
description = "Cron scheduling extension for FastAPI with decorators, async support, Hooks, CLI, and SQLite job tracking."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name="Mehar Umar", email="contact@meharumar.codes" }
]
keywords = ["fastapi", "cron", "scheduler", "background jobs", "tasks", "async crons", "fastapi crons", "crons"]
dependencies = [
  "fastapi>=0.100",
  "croniter>=1.3.0",
  "aiosqlite>=0.18.0",
  "typer[all]>=0.9.0",
  "rich",
  "redis",
  "pydantic>=2.0.0",
  "aiohttp"
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "pytest-asyncio>=0.21.0",
  "pytest-cov>=4.0.0",
  "ruff>=0.1.0",
  "mypy>=1.0.0",
  "types-aiofiles",
  "types-redis",
  "build>=1.0.0",
  "twine>=4.0.0",
]

[project.urls]
"Homepage" = "https://github.com/me-umar/fastapi-crons"
"Documentation" = "https://crons.meharumar.codes"

[tool.setuptools.packages.find]
where = ["."]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
addopts = "-v --strict-markers"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "C4", "PIE", "PT", "RUF"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.coverage.run]
source = ["fastapi_crons"]
omit = ["*/tests/*", "*/__pycache__/*"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "raise AssertionError",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
