name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check .

  build-and-test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12","3.13","3.14"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio httpx 
        pip install .     

    - name: Run tests
      run: pytest tests/
  release:
    #needs: build-and-test
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"    
      - name: Install build tool  # <--- THIS IS THE NEW STEP
        run: pip install build
      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Package to GitHub Release
        if: steps.release.outputs.released == 'true'
        uses: python-semantic-release/upload-to-gh-release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}     
  deploy:
    needs: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install build and twine
        run: pip install build twine  
      - name: Build Package
        run: python -m build         
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/* 
